<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.1 on win32)" generated="20210124 17:14:06.162" rpa="false">
<suite id="s1" name="TestSitePractice" source="E:\Linguagens\Robot Framework\curso-avancado-robot\Web Testing Avançado\SuiteSiteTestePracticePO_antes_de_refatorar\tests\TestSitePractice.robot">
<test id="s1-t1" name="Caso de Teste com PO 01: Remover Produtos do Carrinho">
<kw name="Abrir navegador" library="Resource" type="setup">
<kw name="Open Browser">
<arguments>
<arg>about:blank</arg>
<arg>${BROWSER}</arg>
</arguments>
<msg timestamp="20210124 17:14:06.312" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20210124 17:14:06.312" endtime="20210124 17:14:06.312"></status>
</kw>
<status status="FAIL" starttime="20210124 17:14:06.306" endtime="20210124 17:14:06.312"></status>
</kw>
<kw name="Fechar navegador" library="Resource" type="teardown">
<kw name="Close Browser">
<msg timestamp="20210124 17:14:06.329" level="FAIL">No keyword with name 'Close Browser' found.</msg>
<status status="FAIL" starttime="20210124 17:14:06.328" endtime="20210124 17:14:06.329"></status>
</kw>
<status status="FAIL" starttime="20210124 17:14:06.324" endtime="20210124 17:14:06.329">No keyword with name 'Close Browser' found.</status>
</kw>
<status status="FAIL" starttime="20210124 17:14:06.306" endtime="20210124 17:14:06.329" critical="yes">Setup failed:
No keyword with name 'Open Browser' found.

Also teardown failed:
No keyword with name 'Close Browser' found.</status>
</test>
<status status="FAIL" starttime="20210124 17:14:06.166" endtime="20210124 17:14:06.348"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TestSitePractice">TestSitePractice</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210124 17:14:06.206" level="ERROR">Error in file 'E:\Linguagens\Robot Framework\curso-avancado-robot\Web Testing Avançado\SuiteSiteTestePracticePO_antes_de_refatorar\resources\Resource.robot' on line 2: Importing test library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  E:\Python\Scripts\robot.exe
  e:\python\python39.zip
  e:\python\DLLs
  e:\python\lib
  e:\python
  C:\Users\Ramon\AppData\Roaming\Python\Python39\site-packages
  e:\python\lib\site-packages</msg>
<msg timestamp="20210124 17:14:06.250" level="ERROR">Error in file 'E:\Linguagens\Robot Framework\curso-avancado-robot\Web Testing Avançado\SuiteSiteTestePracticePO_antes_de_refatorar\resources\PO\Home.robot' on line 2: Importing test library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  E:\Python\Scripts\robot.exe
  e:\python\python39.zip
  e:\python\DLLs
  e:\python\lib
  e:\python
  C:\Users\Ramon\AppData\Roaming\Python\Python39\site-packages
  e:\python\lib\site-packages</msg>
<msg timestamp="20210124 17:14:06.274" level="ERROR">Error in file 'E:\Linguagens\Robot Framework\curso-avancado-robot\Web Testing Avançado\SuiteSiteTestePracticePO_antes_de_refatorar\resources\PO\Carrinho.robot' on line 2: Importing test library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  E:\Python\Scripts\robot.exe
  e:\python\python39.zip
  e:\python\DLLs
  e:\python\lib
  e:\python
  C:\Users\Ramon\AppData\Roaming\Python\Python39\site-packages
  e:\python\lib\site-packages</msg>
</errors>
</robot>
